sudo: required
services:
  - docker

before_install:
  - docker build -t erbabydriv/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true erbabydriv/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "ReactDocker-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-147411271495"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
